=== bereilhp/web/web2/ejercicios/json/JSON-Schema/eje1_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "type": "object",
    "title": "Painting",
    "description": "Painting information",
    "additionalProperties": true,
    "required": ["name", "artist", "dimension", "description", "tags"],
    "properties": {
      "name": {
        "type": "string",
        "description": "Painting name"
      },
      "artist": {
        "type": "string",
        "maxLength": 50,
        "description": "Name of the artist"
      },
      "description": {
        "type": ["string", "null"],
        "description": "Painting description"
      },
      "dimension": { "$ref": "#/$defs/dimension" },
      "tags": {
        "type": "array",
        "items": { "$ref": "#/$defs/tag" }
      }
    },
    "$defs": {
      "tag": {
        "type": "string",
        "enum": ["oil", "watercolor", "digital", "famous"]
      },
      "dimension": {
        "type": "object",
        "title": "Painting dimension",
        "description": "Describes the dimension of a painting in cm",
        "additionalProperties": true,
        "required": ["width",  "height"],
        "properties": {
          "width": { "type": "number", "description": "Width of the product", "minimum": 1 },
          "height": { "type": "number", "description": "Height of the product", "minimum": 1 }
        }
      }
    }
  }

=== bereilhp/web/web2/ejercicios/json/JSON-Schema/eje1.json
{
    "name": "Los Jugadores de Cartas",
    "artist": "Paul Cézanne",
    "description": "Los jugadores de cartas (Les Joueurs de cartes en el título francés original) es una serie de cinco cuadros sobre el tema de la partida de cartas, que realizó el pintor francés Paul Cézanne entre 1890 y 1895 (la comenzó estando en Suiza y la acabó en Aix-en-Provence).",
    "dimension": {
        "width": 47.5, 
        "height": 57
    },
    "tags": ["famous", "watercolor"]
}
